# Generated by Django 6.0.4 on 2026-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
